asterostellar/Classification/urls.py
from django.urls import path
from . import views

app_name = 'Classification'
urlpatterns = [
    path('classification/', views.index, name='classification'),
]

asterostellar/PHA/urls.py
from django.urls import path
from . import views

app_name = 'PHA'
urlpatterns = [
    path('pha/', views.index, name='pha')
]

asterostellar/Solar_Distance/urls.py
from django.urls import path
from . import views

app_name = 'Solar_Distance'
urlpatterns = [
    path('solar_distance/', views.index, name='solar_distance')
]

asterostellar/asterostellar/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path('', include('Classification.urls')),
    path('', include('PHA.urls')),
    path('', include('Solar_Distance.urls')),
    path('admin/', admin.site.urls),
]

asterostellar/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('home/', views.index, name='home'),
    path('', views.index, name='home')
]

asterostellar/home/models.py
from django.db import models

# Create your models here.

asterostellar/home/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'home.html')

asterostellar/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{{ settings.APP_NAME }}{% endblock %}</title>
         <!-- Jquery -->
         <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-lightness/jquery-ui.css" crossorigin="anonymous">
         <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
         <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js" crossorigin="anonymous"></script>
        <!-- Semantic UI -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"></script>
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js" crossorigin="anonymous"></script>
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/v4-shims.css">

        {% block head %}
        {% endblock head %}


    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light" style="padding: 1rem; background-color: #12151c">
            <span class="navbar-brand mb-0 h1" style="color: white;">Astrostellar</span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                      <a class="nav-link" style="color: white;" href="{% url 'home:home' %}">Home ! <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" style="color: white;" href="{% url 'Classification:classification' %}">Classify</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: white;" href="{% url 'PHA:pha' %}">Hazardous?</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" style="color: white;" href="{% url 'Solar_Distance:solar_distance' %}">Distance from the Sun</a>
                    </li>
                  </ul>
            </div>
        </nav>

        <div class=bg>
        {% block content %}
        {% endblock content %}
        </div>

    </body>

</html>

asterostellar/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link href="{% static 'css/home.css' %}" rel="stylesheet" type="text/css">
{% endblock head %}


{% block content %}
    <div class="ui raised very padded  container segment astrostellar">
        <h1 class="ui header">Astrostellar</h1>
        <p>The space race has changed our understanding of the universe at an unimaginable pace. Even today, scientists spend their time and effort uncovering the secrets of space to gain more insights and to protect Earth from any potential threats. In support of this effort, our objective in this project is to gain more understanding about asteroids, their trajectories and whether they pose a potential threat to Earth.</p>
        <p>In the following pages, you will be able to make the explained predictions</p>
    </div>
    <div class="ui raised very padded  container segment astrostellar">
        <h2 class="whiteTextOverride" class="whiteTextOverride">Classification of the asteroids</h2 class="whiteTextOverride"><p> Asteroids, the celestial wanderers of our solar system, come in various shapes, sizes, and classifications, each with its own orbiting dance around the sun. Let's embark on a cosmic journey to explore their classifications and their proximity to the planets they orbit. </p>
    </div>
    <div class="ui raised very padded  container segment astrostellar">
        <h2 class="whiteTextOverride">Hazardous or not?:</h2 class="whiteTextOverride"><p>Exploring the Cosmos: Predicting Minimal Orbital Intersection Distance for Astronomical Collision Risk Assessment.</p>
        <p>Our mission is to assess the potential risks of collisions between asteroids and other astronomical objects with unparalleled precision.Through cutting-edge computational models and meticulous analysis of orbital data, we offer insights into the intricate dance of celestial bodies and the potential for close encounters. Our goal is to provide valuable information to astronomers, space agencies, and enthusiasts alike, empowering them to understand and mitigate the risks posed by cosmic collisions.</p>
    </div>
    <div class="ui raised very padded  container segment astrostellar">
        <h2 class="whiteTextOverride">Distance from the Sun</h2 class="whiteTextOverride">
        <p>Asteroids, those nomadic remnants of our solar system's formation, embark on a celestial journey that brings them closest and farthest from the radiant embrace of the Sun</p>
        <div class="ui divider"></div>
        <h3 class="whiteTextOverride">Nearest to the Sun (Perihelion):</h3 class="whiteTextOverride">
        <p>When asteroids reach their perihelion, they are at their closest point to the Sun in their elliptical orbits. This proximity brings them to searing temperatures and intense solar radiation. Perihelion distances can vary greatly depending on the asteroid's orbit, but generally, asteroids can get as close as a few million kilometers from the Sun's surface. Some asteroids with highly eccentric orbits, like members of the Atira or Amor groups, can even have perihelion distances closer than Mercury's average distance from the Sun</p>
        <div class="ui divider"></div>
        <h3 class="whiteTextOverride">Farthest from the Sun (Aphelion)</h3 class="whiteTextOverride">
        <p>Conversely, at aphelion, asteroids reach their farthest point from the Sun in their orbits. This distance can vary significantly depending on the asteroid's orbital eccentricity. For asteroids within the main asteroid belt, aphelion distances typically range from about 2 to 3 astronomical units (AU), with 1 AU being the average distance from the Earth to the Sun. However, certain asteroids with highly eccentric orbits, such as those in the Jupiter-family or Halley-type groups, can have aphelion distances stretching well beyond the orbit of Jupiter, sometimes even extending into the outer reaches of the solar system.</p>
    </div>
{% endblock content%}